application: application-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: 2.3

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /style.css
  static_files: static/style.css
  upload: static/style.css

- url: /application.js
  static_files: static/application.js
  upload: static/application.js

- url: /_ah/mail/.+
  script: email_handler.app
  login: admin

- url: /_cron/.+
  script: cron.app
  login: admin

- url: /.*
  script: api.app

env_variables:
  SESSION_SECRET_KEY: 'session-secret-key'