application: tethbox
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /stylesheets
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /_ah/mail/.+
  script: email_handler.app
  login: admin

- url: /.*
  script: main.app